name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.0.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }} 
            
      - name: Authenticate to Google Cloud Artifact Registry
        run: gcloud auth configure-docker
            
      - name: Build and push Docker image to Artifact Registry
        id: build-image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/google-actions:${{ github.sha }} .
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/google-actions:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/google-actions:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/google-actions:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/google-actions:latest
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/google-actions:${{ github.sha }}
          service: Google.Actions
          region: ${{ secrets.GCP_CLOUDRUN_REGION }}
          platform: managed
          memory: 512Mi
          concurrency: 80
          max-instances: 1
          allow-unauthenticated: true

      - name: Upload Outputs
        uses: actions/upload-artifact@v2
        with:
          name: cloudrun-outputs
          path: ${{ runner.workspace }}

      - name: Print Cloud Run URL
        run: |
          echo "Cloud Run URL: ${{ steps.deploy.outputs.url }}" || true
