name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.0.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: |
            ${{ secrets.GCP_SA_KEY }}
            
      - name: Build and push Docker image to Artifact Registry
        id: build-image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_CLOUDRUN_REGION }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT_ID/app-google:$IMAGE_TAG .
          docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/app-google:$IMAGE_TAG
          docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/app-google:latest
        
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/google-actions:${{ github.sha }}
          service: Google.Actions
          region: ${{ secrets.GCP_CLOUDRUN_REGION }}
          platform: managed
          memory: 512Mi
          concurrency: 80
          max-instances: 1
          allow-unauthenticated: true

      - name: Upload Outputs
        uses: actions/upload-artifact@v2
        with:
          name: cloudrun-outputs
          path: ${{ runner.workspace }}

      - name: Print Cloud Run URL
        run: |
          echo "Cloud Run URL: ${{ steps.deploy.outputs.url }}" || true
